#!/usr/bin/env bash
# ChatHouse — containerized APK build.
#
# Produces a self-contained (Metro-less) release APK, debug-signed so it installs
# on any phone, baked to reach a ChatHouse backend at $BACKEND_HOST. The host
# needs only Docker; this script runs INSIDE the builder image.
#
# Inputs (env):
#   BACKEND_HOST   PC LAN IP the phone will reach (e.g. 192.168.1.42), or
#                  127.0.0.1 for the adb-reverse-over-USB mode.  [required]
#   APK_ABIS       comma list of ABIs to build. Default arm64-v8a (covers ~all
#                  modern phones). Add armeabi-v7a for older 32-bit devices.
#   GOOGLE_MAPS_API_KEY  optional; without it the in-app Map tab is blank.
set -euo pipefail

: "${BACKEND_HOST:?BACKEND_HOST must be set (your PC LAN IP, e.g. 192.168.1.42, or 127.0.0.1 for adb-reverse USB)}"
APK_ABIS="${APK_ABIS:-arm64-v8a}"
GOOGLE_MAPS_API_KEY="${GOOGLE_MAPS_API_KEY:-}"

SRC=/src
WORK=/build
OUT=/output

echo "=================================================================="
echo " ChatHouse APK builder"
echo "   BACKEND_HOST = ${BACKEND_HOST}"
echo "   APK_ABIS     = ${APK_ABIS}"
echo "=================================================================="

# 1. Copy the read-only mounted source into a writable work dir. node_modules is
#    a named volume mounted at ${WORK}/node_modules and is EXCLUDED from the sync
#    (and from --delete) so it survives between runs. Build outputs are excluded
#    so they don't leak the host's (possibly Windows-native) artifacts.
echo "==> Syncing source into ${WORK} ..."
mkdir -p "${WORK}"
rsync -a --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude 'backend' \
  --exclude 'artifacts' \
  --exclude 'android/.gradle' \
  --exclude 'android/.cxx' \
  --exclude 'android/build' \
  --exclude 'android/app/build' \
  --exclude 'android/app/.cxx' \
  "${SRC}/" "${WORK}/"

cd "${WORK}"

# 2. Bake the backend endpoints into the app's build-time .env. react-native-dotenv
#    inlines these at bundle time — there is NO runtime server switch, so the APK
#    is frozen to this host. (That's why each backend host gets its own build.)
echo "==> Writing .env (backend host = ${BACKEND_HOST}) ..."
cat > "${WORK}/.env" <<EOF
API_BASE_URL=http://${BACKEND_HOST}:4000/api
WS_BASE_URL=ws://${BACKEND_HOST}:4000
REALTIME_ENABLED=true
ENV=development
SENTRY_DSN=
LIVEKIT_URL=ws://${BACKEND_HOST}:7880
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
EOF

# 3. Permit cleartext HTTP/WS to the chosen host in the RELEASE build. The shipped
#    main config only whitelists localhost/127.0.0.1/10.0.2.2, so a plain LAN IP
#    would otherwise be blocked. This generated config is for LOCAL TESTING only
#    and never touches your git working tree (we edited the copy under ${WORK}).
echo "==> Permitting cleartext to ${BACKEND_HOST} (local test build) ..."
cat > "${WORK}/android/app/src/main/res/xml/network_security_config.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by the Docker APK builder for LOCAL TESTING. Permits cleartext
     HTTP/WS so the app can reach a dev backend over http://<LAN_IP> / ws://. -->
<network-security-config>
  <base-config cleartextTrafficPermitted="true" />
</network-security-config>
EOF

# 4. Install JS dependencies. Cached in the node_modules volume across runs, so
#    only the first build pays the full install cost.
echo "==> Installing npm dependencies ..."
export HUSKY=0                       # don't try to install git hooks in the container
export SENTRY_DISABLE_AUTO_UPLOAD=true  # release build must not try to upload sourcemaps
export CI=1
if [ -f package-lock.json ]; then
  npm ci --no-audit --no-fund
else
  npm install --no-audit --no-fund
fi

# 5. Build the standalone release APK. `assembleRelease` bundles the Hermes JS +
#    assets into the APK (unlike debug, which expects Metro). With no
#    CHATHOUSE_UPLOAD_* keystore provided, build.gradle falls back to the debug
#    keystore, so the output is signed and installable (NOT Play-shippable).
echo "==> Building release APK (ABIs: ${APK_ABIS}) — first run downloads Gradle 9, be patient ..."
cd "${WORK}/android"
sed -i 's/\r$//' ./gradlew 2>/dev/null || true
chmod +x ./gradlew

# Low-memory profile so the build survives on RAM-constrained hosts (this whole
# distribution targets 'any tester', not just big dev boxes). Written into
# GRADLE_USER_HOME so it augments the project's android/gradle.properties without
# editing it. Kotlin compiles in-process (no separate ~1.3GB daemon JVM); a single
# worker keeps peak memory bounded.
mkdir -p "${GRADLE_USER_HOME:-$HOME/.gradle}"
cat > "${GRADLE_USER_HOME:-$HOME/.gradle}/gradle.properties" <<'EOF'
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
EOF

./gradlew :app:assembleRelease \
  -PreactNativeArchitectures="${APK_ABIS}" \
  --no-daemon --max-workers=1

# 6. Export the APK to the mounted output dir with a host-tagged name.
mkdir -p "${OUT}"
APK_SRC="${WORK}/android/app/build/outputs/apk/release/app-release.apk"
if [ ! -f "${APK_SRC}" ]; then
  echo "!! Expected APK not found at ${APK_SRC}" >&2
  ls -R "${WORK}/android/app/build/outputs/apk" >&2 || true
  exit 1
fi
SAFE_HOST="$(echo "${BACKEND_HOST}" | tr '.:' '__')"
APK_DEST="${OUT}/chathouse-${SAFE_HOST}.apk"
cp -f "${APK_SRC}" "${APK_DEST}"

BYTES=$(stat -c%s "${APK_DEST}" 2>/dev/null || wc -c < "${APK_DEST}")
echo "=================================================================="
echo " DONE ✓  artifacts/$(basename "${APK_DEST}")  (${BYTES} bytes)"
echo ""
echo " Install on an Android phone (enable 'install unknown apps'):"
echo "   • copy the .apk to the phone and tap it, OR"
echo "   • adb install -r artifacts/$(basename "${APK_DEST}")"
echo ""
echo " Make sure the phone and this PC are on the SAME Wi-Fi and the PC"
echo " firewall allows inbound TCP 4000 + 7880 and UDP 41100-41199."
echo "=================================================================="
